# Generated by Django 5.0.4 on 2024-05-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsapi', '0003_bayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_pdf',
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='QRCode'),
        ),
    ]
