# Generated by Django 5.0.4 on 2024-05-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsapi', '0004_remove_booking_booking_pdf_booking_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='your_date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
